name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: "Chceckout Code"
      uses: actions/checkout@v4

    - name: Set up .env variables
      run:  | 
        echo "MYSQL_USER=${{secrets.MYSQL_USER}}" >> .env
        echo "MYSQL_PASSWORD=${{secrets.MYSQL_PASSWORD}}" >> .env

        
    - name: Build the Docker image
      run: docker compose up -d --build --remove-orphans

    - name: Cleanup
      run: docker image prune -f
